import type { AuthLocalization } from "@neondatabase/auth-ui";

export const frenchAuthLocalization = {
  APP: "Application Lyreah",
  ACCOUNT: "Compte",
  ADD_PASSKEY: "Ajouter une clé d’accès",
  ALREADY_HAVE_AN_ACCOUNT: "Vous avez déjà un compte ?",
  AVATAR: "Photo de profil",
  AVATAR_DESCRIPTION: "Choisissez l’image qui vous représentera sur Lyreah.",
  AVATAR_INSTRUCTIONS: "Formats image courants acceptés.",
  CANCEL: "Annuler",
  CHANGE_PASSWORD: "Modifier le mot de passe",
  CHANGE_PASSWORD_DESCRIPTION:
    "Saisissez votre mot de passe actuel, puis choisissez-en un nouveau.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Utilisez au moins 8 caractères.",
  CHANGE_PASSWORD_SUCCESS: "Votre mot de passe a été modifié.",
  CONFIRM_PASSWORD: "Confirmer le mot de passe",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirmez le mot de passe",
  CONFIRM_PASSWORD_REQUIRED: "La confirmation du mot de passe est requise",
  CONTINUE: "Continuer",
  CURRENT_PASSWORD: "Mot de passe actuel",
  CURRENT_PASSWORD_PLACEHOLDER: "Mot de passe actuel",
  CURRENT_SESSION: "Session actuelle",
  DELETE: "Supprimer",
  DELETE_ACCOUNT: "Supprimer mon compte",
  DELETE_ACCOUNT_DESCRIPTION:
    "Supprime définitivement votre compte Lyreah et toutes les données qui lui sont associées.",
  DELETE_ACCOUNT_INSTRUCTIONS:
    "Cette action est irréversible. Une confirmation vous sera demandée.",
  DELETE_ACCOUNT_SUCCESS: "Votre compte a été supprimé.",
  DELETE_ACCOUNT_VERIFY:
    "Consultez votre messagerie pour confirmer la suppression du compte.",
  DELETE_AVATAR: "Supprimer la photo",
  DONE: "Terminer",
  DONT_HAVE_AN_ACCOUNT: "Vous n’avez pas encore de compte ?",
  EMAIL: "Adresse e-mail",
  EMAIL_DESCRIPTION: "Adresse utilisée pour vous connecter à Lyreah.",
  EMAIL_INSTRUCTIONS: "Saisissez une adresse e-mail valide.",
  EMAIL_IS_THE_SAME: "Cette adresse e-mail est déjà utilisée pour ce compte.",
  EMAIL_PLACEHOLDER: "vous@exemple.fr",
  EMAIL_REQUIRED: "L’adresse e-mail est requise",
  EMAIL_VERIFICATION:
    "Un nouveau message de vérification vient de vous être envoyé.",
  EMAIL_VERIFY_CHANGE:
    "Consultez votre messagerie pour confirmer la nouvelle adresse.",
  EMAIL_CAN_NOT_BE_UPDATED: "Cette adresse e-mail ne peut pas être modifiée",
  EMAIL_NOT_VERIFIED: "L’adresse e-mail n’est pas encore vérifiée",
  FAILED_TO_CREATE_SESSION: "La session n’a pas pu être créée",
  FAILED_TO_GET_SESSION: "La session n’a pas pu être récupérée",
  FAILED_TO_UNLINK_LAST_ACCOUNT:
    "La dernière méthode de connexion ne peut pas être dissociée",
  FAILED_TO_UPDATE_USER: "Le profil n’a pas pu être mis à jour",
  FORGOT_PASSWORD: "Mot de passe oublié",
  FORGOT_PASSWORD_ACTION: "Envoyer le lien de réinitialisation",
  FORGOT_PASSWORD_DESCRIPTION:
    "Indiquez votre adresse e-mail pour réinitialiser votre mot de passe.",
  FORGOT_PASSWORD_EMAIL:
    "Consultez votre messagerie pour poursuivre la réinitialisation.",
  FORGOT_PASSWORD_LINK: "Mot de passe oublié ?",
  GO_BACK: "Retour",
  INVALID_EMAIL: "Adresse e-mail invalide",
  INVALID_EMAIL_OR_PASSWORD: "Adresse e-mail ou mot de passe incorrect",
  INVALID_PASSWORD: "Mot de passe incorrect",
  IS_INVALID: "est invalide",
  IS_REQUIRED: "est requis",
  IS_THE_SAME: "n’a pas été modifié",
  LINK: "Associer",
  NAME: "Pseudo",
  NAME_DESCRIPTION: "Le nom affiché dans Lyreah et dans l’en-tête du site.",
  NAME_INSTRUCTIONS: "Utilisez au maximum 32 caractères.",
  NAME_PLACEHOLDER: "Votre pseudo",
  NEW_PASSWORD: "Nouveau mot de passe",
  NEW_PASSWORD_PLACEHOLDER: "Nouveau mot de passe",
  NEW_PASSWORD_REQUIRED: "Le nouveau mot de passe est requis",
  OR_CONTINUE_WITH: "Ou continuer avec",
  PASSKEY: "Clé d’accès",
  PASSKEYS: "Clés d’accès",
  PASSKEYS_DESCRIPTION: "Gérez vos clés d’accès sécurisées.",
  PASSKEYS_INSTRUCTIONS: "Connectez-vous sans mot de passe sur vos appareils.",
  PASSWORD: "Mot de passe",
  PASSWORD_PLACEHOLDER: "Mot de passe",
  PASSWORD_REQUIRED: "Le mot de passe est requis",
  PASSWORDS_DO_NOT_MATCH: "Les mots de passe ne correspondent pas",
  PASSWORD_TOO_LONG: "Le mot de passe est trop long",
  PASSWORD_TOO_SHORT: "Le mot de passe est trop court",
  PROVIDER_NOT_FOUND: "Cette méthode de connexion est introuvable",
  PROVIDERS: "Méthodes de connexion",
  PROVIDERS_DESCRIPTION: "Gérez les services associés à votre compte.",
  REQUEST_FAILED: "La demande n’a pas pu aboutir",
  RESEND_VERIFICATION_EMAIL: "Renvoyer l’e-mail de vérification",
  RESET_PASSWORD: "Réinitialiser le mot de passe",
  RESET_PASSWORD_ACTION: "Enregistrer le nouveau mot de passe",
  RESET_PASSWORD_DESCRIPTION: "Choisissez votre nouveau mot de passe.",
  RESET_PASSWORD_SUCCESS: "Votre mot de passe a été réinitialisé.",
  REVOKE: "Déconnecter",
  SAVE: "Enregistrer",
  SECURITY: "Sécurité",
  SESSION_EXPIRED:
    "Votre session a expiré. Reconnectez-vous pour effectuer cette action.",
  SESSION_NOT_FRESH:
    "Pour votre sécurité, reconnectez-vous avant d’effectuer cette action.",
  SESSIONS: "Appareils connectés",
  SESSIONS_DESCRIPTION:
    "Consultez vos sessions actives et retirez l’accès à un appareil.",
  SETTINGS: "Paramètres",
  SET_PASSWORD: "Définir un mot de passe",
  SET_PASSWORD_DESCRIPTION:
    "Recevez un e-mail pour ajouter un mot de passe à votre compte.",
  SIGN_IN: "Connexion",
  SIGN_IN_ACTION: "Se connecter",
  SIGN_IN_DESCRIPTION: "Connectez-vous pour retrouver votre bibliothèque.",
  SIGN_IN_WITH: "Se connecter avec",
  SIGN_OUT: "Se déconnecter",
  SIGN_UP: "Inscription",
  SIGN_UP_ACTION: "Créer mon compte",
  SIGN_UP_DESCRIPTION: "Créez votre compte pour commencer votre bibliothèque.",
  SIGN_UP_EMAIL: "Consultez votre messagerie pour vérifier votre adresse.",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "Ce compte est déjà associé",
  UNLINK: "Dissocier",
  UNKNOWN: "Appareil inconnu",
  UPDATE: "Mettre à jour",
  UPDATED_SUCCESSFULLY: "a bien été mis à jour",
  UPLOAD: "Importer",
  UPLOAD_AVATAR: "Choisir une photo",
  USER_ALREADY_EXISTS: "Un compte existe déjà avec cette adresse e-mail",
  USER_ALREADY_HAS_PASSWORD:
    "Ce compte possède déjà un mot de passe. Utilisez-le pour continuer.",
  USER_NOT_FOUND: "Compte introuvable",
  VERIFY_YOUR_EMAIL: "Vérifiez votre adresse e-mail",
  VERIFY_YOUR_EMAIL_DESCRIPTION:
    "Consultez votre messagerie ou demandez un nouvel e-mail de vérification.",
} satisfies AuthLocalization;
